config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users
  root 'logs#index'
  resources  :logs do
    resources :comments, only: [:create]
  end 
  resources :users, only: :show 
  resources :comments, only: [:destroy]
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :log

  validates :text, presence: true
  validates :user_id, presence: true
  validates :log_id, presence: true
end

app/models/day.rb
class Day < ActiveHash::Base
  self.data = [
    { id: 1, name: '日曜日' },
    { id: 2, name: '月曜日' },
    { id: 3, name: '火曜日' },
    { id: 4, name: '水曜日' },
    { id: 5, name: '木曜日' },
    { id: 6, name: '金曜日' },
    { id: 7, name: '土曜日' }
  ]

  include ActiveHash::Associations
  has_many :logs
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '男' },
    { id: 2, name: '女' },
    { id: 3, name: 'その他' },
    { id: 4, name: '答えない' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :log
end

app/models/log.rb
class Log < ApplicationRecord
  validates :title, presence: true
  validates :day_id, presence: true
  validates :user_id, presence: true

  has_many :trainings, dependent: :destroy
  accepts_nested_attributes_for :trainings, allow_destroy: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :tag_relations, dependent: :destroy
   has_many :tags, through: :tag_relations

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :day

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relations, dependent: :destroy
  has_many :logs, through: :tag_relations
  validates :name, uniqueness: true
end

app/models/tag_relation.rb
class TagRelation < ApplicationRecord
  belongs_to :log
  belongs_to :tag  
end

app/models/training.rb
class Training < ApplicationRecord
  with_options presence: true do
    validates :training
    with_options numericality: { only_integer: true, message: 'is invalid. Input half-width number.' } do
      validates :weight_kg
      validates :weight_lb
      validates :rep
      validates :set_number
    end
  end

  belongs_to :log
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :gender_id
  end

  has_many :logs, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender

  def liked_by?(log_id)
    likes.where(log_id: log_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_paremeters, if: :devise_controller?

  private

  def configure_permitted_paremeters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :gender_id, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    if @comment.valid?
      @comment.save
      redirect_to log_path(@comment.log)
    else
      @log = @comment.log
      @comments = @log.comments
      render template: 'logs/show'
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    redirect_to log_path(comment.log) if comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, log_id: params[:log_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :log_params

  def create
    Like.create(user_id: current_user.id, log_id: params[:id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, log_id: params[:id]).destroy
  end

  private

  def log_params
    @log = Log.find(params[:id])
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_log, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]

  def index
    @logs = Log.all.includes(
      [:user, :trainings]
    ).page(params[:page]).per(12).order('created_at DESC')
  end

  def new
    @log = Log.new
  end

  def create
    @log = Log.new(log_params)
    if @log.valid?
      @log.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @log.comments.includes(:user).order('created_at DESC')
    @likes_count = Like.where(log_id: @log.id).count
  end

  def edit
  end

  def update
    if @log.update(log_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if current_user.id == @log.user_id && @log.destroy
  end

  private

  def log_params
    params.require(:log).permit(
      :title,
      :day_id,
      trainings_attributes: [
        :id,
        :training,
        :weight_kg,
        :weight_lb,
        :rep,
        :set_number,
        :_destroy
      ]
    ).merge(user_id: current_user.id)
  end

  def find_log
    @log = Log.find(params[:id])
  end

  def move_to_index
    log = Log.find(params[:id])
    redirect_to action: :index unless user_signed_in? && current_user.id == log.user_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @logs = @user.logs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Fitlog</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
      <%= stylesheet_link_tag 'application', media: 'all'%>
      <link rel="stylesheet" href="stylesheets/style.css">
  </head>
  <body>
    <%= yield %>
    <footer class=”footer”>
       Copyright FitLog 2021.
    </footer>   
  </body>
</html>

app/views/likes/_like.html.erb
<% if current_user.liked_by?(log.id) %>
  <%= link_to destroy_like_path(log), class: 'like-link', method: :DELETE, remote: true do %>
    <i class="fa fa-heart unlike-btn"></i>
  <% end %>
  <%= log.likes.count %>
<% else %>
  <%= link_to create_like_path(log), class: 'like-link', method: :POST, remote: true do %>
    <i class="fa fa-heart like-btn"></i>
  <% end %> 
  <%= log.likes.count %>  
<% end %>

app/views/likes/create.js.erb
document.getElementById('log_<%= @log.id %>').innerHTML = '<%= j(render partial: 'like', locals:{log: @log }) %>'

app/views/likes/destroy.js.erb
document.getElementById('log_<%= @log.id %>').innerHTML = '<%= j(render partial: 'like', locals:{log: @log }) %>'

app/views/logs/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <%= link_to image_tag("logo.png", class:'navbar-brand'), "/" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
   <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <% if user_signed_in? %>
    <ul class="nav navbar-nav ">
      <li class="nav-item active">
        <%= link_to 'ライブラリ', page_path('library'),class: 'nav-link' %>
      </li>
      <li class="nav-item active ">
        <%= link_to "投稿する", new_log_path , class: "post", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span><%= current_user.nickname %>さん</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "マイページ", "/users/#{current_user.id}",class: "dropdown-item" %>
          <%= link_to "ログアウト", destroy_user_session_path,method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
     <% else %>
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "ログイン", new_user_session_path, class: "post", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "post", class: "nav-link"%> 
        </li>
     </ul>
    </div>
   </nav>
<% end %>  
</header>     

app/views/logs/_log.html.erb
<div class="col-xl-4 md-4 col-sm-6">
  <div class="card-group">
    <div class="d-flex justify-content-xl-around mx-auto">
      <div class="card p-3 mt-3 shadow-none bg-light border-danger mx-auto" style="width: 18rem;"> 
        <div class="card-header d-inline text-muted "> 
          <span class="training-name"><%= link_to log.title, log_path(log[:id]), method: :get, class: 'log-title' %>の日</span>
          <span class="training-day">（<%= log.day.name %>）</span>
          <span class="user-name">by <%= link_to "#{log.user.nickname}", user_path(log.user.id), class: 'log-user'%></span>
          <% log.tags.each do |tag|%>
            <%= tag.name %>
          <% end %>  
        </div> 
        <% log.trainings.each do |training| %>
        <ul class="list-group list-group-flush"> 
          <li class="list-group-item"> 
            <%= training.training %>
            <%= training.weight_kg %><span>kg</span>
            <%= training.weight_lb %><span>lb</span>
            <%= training.rep %><span>回</span>
            <%= training.set_number %><span>セット</span>
          </li> 
        </ul>  
        <% end %> 
      </div> 
    </div> 
  </div>
 </div>

app/views/logs/_log_form.html.erb
<div class="nested-fields">
  <div class="form-row">
    <div class="col-xl-3 col-md-3 col-sm-4">
      <%= f.text_field :training, placeholder:"種目",class: 'form_text form-control' %>
    </div>
    <div class="col-xl-2 col-md-2 col-sm-6">
      <%= f.text_field :weight_kg, placeholder:"重量",class: 'weight form_text form-control' %>
    </div>
    <span class="unit"><strong>kg</strong></span>
    <div class="col-xl-2 col-md-2 col-sm-6">
      <%= f.text_field :weight_lb, placeholder:'ポンド',class: 'weight-lb form-control'%>
    </div>
    <span class="unit"><strong>lb</strong></span>
    <div class="col-xl-2 col-md-2 col-sm-6">
      <%= f.text_field :rep, placeholder: "回数", class: 'form-control' %>
    </div>
    <div class="col-xl-2 col-md-2 col-sm-6">
      <%= f.text_field :set_number, placeholder: "セット数", class:'form-control'%>
    </div>
    <%= link_to_remove_association 'ー', f, class: "btn btn--red btn--cubic btn-circle" %>
  </div>  
</div>

app/views/logs/edit.html.erb
<%= render "header"%>
  <main class="new-main">
    <h2 class="page-heading">LOG EDIT</h2> 
    <%= render 'devise/shared/error_messages', model: @log%>
    <div class="new-log-form">
      <%= form_with model: @log , local: true  do |f| %>
      <form>
        <div class="form-row">
          <div class="col-7">
            <%= f.text_field :title, placeholder: "今日は何のトレーニングの日？", class: 'form-control' %> 
          </div>  
          <div class="col-2">
            <%= f.collection_select(:day_id, Day.all, :id, :name, {include_blank: '選択して下さい'}, {class:"select-box form-control", id:"item-category"}) %>
          </div>  
       </div>  
       <div class="add_logs">
        <%= f.fields_for :trainings, @log.trainings do |form| %>
        <%= render 'logs/log_form', {f:form} %>
        <% end %>
        <div class="append_logs"></div>
       <div class="links">
        <%=link_to_add_association 'ADD', f, :trainings, partial: 'logs/log_form',data: { association_insertion_method: 'append' }, class: 'btn btn--red btn--radius btn--cubic' %>
       </div>
        <%= f.submit "SEND", class: 'btn btn--orange btn--cubic btn--shadow', id: "submit"  %>
       <% end %>
      </form>
    </div>
</main>

app/views/logs/index.html.erb
<%= render "header"%>
<main>
<div class="top-container">
  <div class="title-container">
  <h1>LOG TO BE FIT.</h1>
  <h2>THE MORE YOU LOG, </br>THE MORE YOU GET FIT.</h2>
  <p>FIT LOGは、筋トレ記録アプリです。
  </p>
  </div>
</div>
 <div class="heading-index"><h2>New Logs</h2></div>
  <div class="container">
      <div class="row">
        <%= render partial: "log", collection: @logs %>
    </div> 
  </div>
  <%= paginate @logs %>
</main> 

app/views/logs/new.html.erb
<%= render "header"%>
<main class="new-main">
 <h2 class="page-heading">NEW LOG</h2> 
  <%= render 'devise/shared/error_messages', model: @log%>
    <div class="new-log-form">
      <%= form_with model: @log , local: true  do |f| %>
       <form>
        <div class="form-row">
        <div class="col-7">
          <%= f.text_field :title, placeholder: "今日は何のトレーニングの日？", class: 'form-control' %> 
          </div>  
          <div class="col-3">
            <%= f.collection_select(:day_id, Day.all, :id, :name, {include_blank: '選択して下さい'}, {class:"select-box form-control", id:"item-category"}) %>
          </div>
          <div class="col-7">
          <%= f.text_field :tag_ids, class: "form-control", id: 'tag_ids',
          placeholder: "タグをつける。複数つけるには、','で区切ってください。"%>
          </div>
         </div> 
      <div class="add_logs">
      <%= f.fields_for :trainings, @log.trainings.build do |form| %>
      <%= render 'logs/log_form', {f:form} %>
      <div class="append_logs"></div>
      <div class="links">
      <%=link_to_add_association 'ADD', f, :trainings, partial: 'logs/log_form',data: { association_insertion_method: 'append' }, class: 'btn btn--red btn--radius btn--cubic ' %>
      </div>
    <% end %>
    <%= f.submit "SEND", class: 'btn btn--orange btn--cubic btn--shadow', id: "submit"  %></span>
    <% end %>
   </form> 
   </div> 
</main>

app/views/logs/show.html.erb
<%= render "logs/header" %>
<main class="show-main">
<table class="table table-bordered border-danger">
  <thead class="thead">
    <tr class="table-danger">  
       <th scope="col">
          <div class="training-table"><span class="training-name"><%= @log.title %>の日</span>
          <span class="training-day">(<%= @log.day.name %>)</span></div>
          by <%= link_to "#{@log.user.nickname}", user_path(@log.user_id), class: 'user-name text-muted'%>
          <% if user_signed_in? && current_user.id == @log.user_id%>
          <div class="training-manage">
            <%= link_to edit_log_path(@log[:id]) , class:'btn btn-sm btn-secondary text-white', method: :get do %>
              <i class="fas fa-pen "></i>
             <% end %>
            <%= link_to log_path(@log[:id]) , class: "btn btn-sm btn-danger text-white", method: :delete do %>
              <i class="far fa-trash-alt"></i> 
            <% end %>  
          </div>
          <% end %>  
          <div id="log_<%= @log.id %>">
        <%= render 'likes/like', log: @log %>
        </div>
      </th>
    </tr>
  </thead>
   <tbody>
    <% @log.trainings.each do |training| %>
    <tr class="border-danger">
      <td>
        <div class="title-text"><strong><%= training.training %></strong></div>
        <div class="training-text"><%= training.weight_kg %><span>kg</span></div>
        <div class="training-text"><%= training.weight_lb  %><span>lb</span></div>
        <div class="training-text"><%= training.rep %><span>回</span></div>
        <div class="training-text"><%= training.set_number %><span>セット</span></div>
       </td>
       </tr>
    <% end %>  
  </tbody> 
</table>
<div class="log-comments">
  <% if user_signed_in? %>
  <%= form_with model:[@log,@comment], local: true do |f| %>
  <div class="field">
   <div class="comment-heading"> 
    <%= f.label :text, "comment"  %><br />
   </div> 
    <%= f.text_area :text, class: 'form-control comment', placeholder:'コメントする', rows: "3" %>
  </div>
  <div class="actions">
  <%= f.submit "送信", class: 'btn btn--orange btn--cubic btn--shadow' %>
  </div>
  <% end %>
  <% end %>
    <ul class="comments-list">
    <% @comments.each do |comment| %>  
      <li class="comment-list" >
       <%= comment.text %>
       <strong><div class="user-comment">by <%= link_to comment.user.nickname, user_path(comment.user.id), class: 'comment-user' %> </strong>
       <% if user_signed_in? && current_user.id == comment.user_id%>
       <%= link_to comment_path(comment.id) , class: "btn btn-sm btn-outline-danger text-dark", method: :delete do %>
        <i class="far fa-trash-alt"></i> 
       <% end %>  
      <% end %>
      </div>
     </li>
    
   <% end %>    
   </ul> 
</div>
</main>

app/views/pages/library.html.erb
<%= render "logs/header"%>
<main>
  <h2 class="page-heading">Lower Body Training</h2>
  <div class="container-library">
    <div class="row">
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/JXdGBp_YYz0?start=3" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div> 
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/YoFT00akxjc?start=3" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/Pcj52FBPvko?start=3" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/oR4iY29PBjA?start=8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/RCWkvwz7DoU?start=1" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/6W-ViLupxKE?start=93" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>
  </div>
  <h2 class="page-heading">Upper Body Training</h2>
  <div class="container-library">
    <div class="row">
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/Mfaf7lY3w38?start=5" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/WrobhcIeWhM?start=6" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/9_JPTA3ie7k?start=5" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/seUCEgPsBtc?start=8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/8WL0m0vLAPo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="col xl3 l4 m6 xs12">
        <iframe width="360" height="215" src="https://www.youtube.com/embed/FGU9j1P5L-w" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>
  </div>
  <h2 class="page-heading">Core Body Training</h2>
    <div class="container-library">
      <div class="row">
        <div class="col xl3 l4 m6 xs12">
          <iframe width="360" height="215" src="https://www.youtube.com/embed/bdWT9_EdZZ0?start=7" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="col xl3 l4 m6 xs12">
          <iframe width="360" height="215" src="https://www.youtube.com/embed/9LCGaXo3PMY?start=3" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="col xl3 l4 m6 xs12">
          <iframe width="360" height="215" src="https://www.youtube.com/embed/97boSjZ0erk?start=4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="col xl3 l4 m6 xs12">
          <iframe width="360" height="215" src="https://www.youtube.com/embed/3qjoXDTuyOE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="col xl3 l4 m6 xs12">
          <iframe width="360" height="215" src="https://www.youtube.com/embed/cuSQdnKjU0E?start=56" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="col xl3 l4 m6 xs12">
          <iframe width="360" height="215" src="https://www.youtube.com/embed/fPeaswyqkW8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      </div>
    </div>
</main>

app/views/users/show.html.erb
<%= render "logs/header"%>
<main class="user-main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}'s profile "%>
      </h2>
      <div class="profile">
      <table class="table table-borderd table-danger">
        <tbody class="profile-table">
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">性別</th>
            <td class="table__col2"><%= @user.gender.name %></td>
          </tr>
        </tbody>
      </table>
      </div>
      </div >
      <h2 class="page-heading">
        <%= "#{@user.nickname}'s logs "%>
      </h2>
      <div class="container">
      <div class="row">
      <%= render partial: "logs/log", collection: @logs %>
      </div>
    </div>
  </div>
</main>